// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    [Migration("20220228190142_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutorKnjiga", b =>
                {
                    b.Property<int>("AutoriID")
                        .HasColumnType("int");

                    b.Property<int>("KnjigeID")
                        .HasColumnType("int");

                    b.HasKey("AutoriID", "KnjigeID");

                    b.HasIndex("KnjigeID");

                    b.ToTable("AutorKnjiga");
                });

            modelBuilder.Entity("IznajmljivanjeKnjiga", b =>
                {
                    b.Property<int>("IznajmljivanjaID")
                        .HasColumnType("int");

                    b.Property<int>("KnjigeID")
                        .HasColumnType("int");

                    b.HasKey("IznajmljivanjaID", "KnjigeID");

                    b.HasIndex("KnjigeID");

                    b.ToTable("IznajmljivanjeKnjiga");
                });

            modelBuilder.Entity("WebAPI.Models.Autor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Ime");

                    b.Property<string>("Prezime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Prezime");

                    b.HasKey("ID");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("WebAPI.Models.Clan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Ime");

                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JMBG");

                    b.Property<string>("Prezime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Prezime");

                    b.HasKey("ID");

                    b.ToTable("Clanovi");
                });

            modelBuilder.Entity("WebAPI.Models.Iznajmljivanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2")
                        .HasColumnName("Datum");

                    b.HasKey("ID");

                    b.HasIndex("ClanID");

                    b.ToTable("Iznajmljivanja");
                });

            modelBuilder.Entity("WebAPI.Models.Knjiga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojStrana")
                        .HasColumnType("int")
                        .HasColumnName("BrojStrana");

                    b.Property<int>("Godina")
                        .HasColumnType("int")
                        .HasColumnName("Godina");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("AutorKnjiga", b =>
                {
                    b.HasOne("WebAPI.Models.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Knjiga", null)
                        .WithMany()
                        .HasForeignKey("KnjigeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IznajmljivanjeKnjiga", b =>
                {
                    b.HasOne("WebAPI.Models.Iznajmljivanje", null)
                        .WithMany()
                        .HasForeignKey("IznajmljivanjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Knjiga", null)
                        .WithMany()
                        .HasForeignKey("KnjigeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI.Models.Iznajmljivanje", b =>
                {
                    b.HasOne("WebAPI.Models.Clan", "Clan")
                        .WithMany("Iznajmljivanja")
                        .HasForeignKey("ClanID");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("WebAPI.Models.Clan", b =>
                {
                    b.Navigation("Iznajmljivanja");
                });
#pragma warning restore 612, 618
        }
    }
}
